import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner"
import { Navbar } from "@/components/layout/navbar/Navbar";
import { Footer } from "@/components/layout/footer/Footer";
import {
  SidebarProvider,
  Sidebar,
  SidebarContent,
  SidebarInset,
} from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/layout/app-sidebar/AppSidebar.tsx";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body className="min-h-full flex flex-col">

        <SidebarProvider>

          {/* SIDEBAR */}
          <Sidebar>
           <AppSidebar />
          </Sidebar>

          {/* MAIN CONTENT */}
          <SidebarInset>
            <Navbar />
            {children}
            <Footer />
          </SidebarInset>

        </SidebarProvider>

        <Toaster />
      </body>
    </html>
  )
}